### ISSUE TITLE
Dynamic project & labels

### ISSUE THREAD

**Issue by creekorful** [creekorful/todosync#3]
```toml
[config]
gitlab_token = "" # the token to connect with Gitlab
todoist_token = "" # the token to connect with Todoist
database_file = "" # where to save the local cache

[[sources]]
url = "https://gitlab.com/creekorful/test" # source url
labels = [0] # the optional label to add to the task
default = 0 # default task section (can be either project or section)
todo = 0 # where we put task with todo status (can be either project or section)
in_progress = 0 # where we put task with todo in_progress (can be either project or section)

[[sources]]
url = "https://gitlab.com/creekorful/test-2"
labels = [0]
default = 0
todo = 0
in_progress = 0
```
